# Generated by Django 5.0.3 on 2024-03-20 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trekkings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='users',
        ),
    ]
