# Generated by Django 5.0.3 on 2024-03-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekkings', '0002_rename_user_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password1', models.CharField(max_length=15)),
                ('repassword', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
