# Generated by Django 5.0.3 on 2024-03-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trekkings', '0003_reg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reg',
            new_name='Register',
        ),
    ]
