# Generated by Django 5.0.3 on 2024-03-28 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trekkings', '0004_rename_reg_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='SamUser',
        ),
    ]
