# Generated by Django 5.0.3 on 2024-03-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekkings', '0006_login_delete_samuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='password1',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
